# redis server
#redis:
#  restart: always
#  image: dockerfile/redis
#  volumes: /root/redis-data:/data
#  ports:
#   - "6379:6379"
#  expose:
#   - "6379"

#docker run -e USERNAME=ooiui -e PASS=ooiui -d --name ooiuidb -v $HOME/postgres_data:/var/lib/postgresql oceanzus/docker_postgis
ooiuidb:
  restart: always
  image: oceanzus/docker_postgis
  volumes:
   - $HOME/postgres_data:/var/lib/postgresql
  environment:
    USERNAME: ooiui
    PASS: ooiui
  ports:
   - "5432:5432"
  expose:
   - "5432"

#docker run -e HOST_IP=0.0.0.0 -e DB_PORT=5432 -e DB_USER=ooiui -e DB_PASS=ooiui -e DB_HOST=ooiuidb -e DB_NAME=ooiuidev -e DB_RESET=true -d --name ooiuiservices --link ooiuidb:ooiuidb oceanzus/ooi-ui-services-deploy
ooiuiservices:
  restart: always
  image: oceanzus/ooi-ui-services
  ports:
   - "4000:4000"
  expose:
   - "4000"
  environment:
    HOST_IP: 0.0.0.0
    DB_PORT: 5432
    DB_USER: ooiui
    DB_PASS: ooiui
    DB_HOST: ooiuidb
    DB_NAME: ooiui
    DB_RESET: true
    DB_SCHEMA: ooiui
    DEFAULT_ADMIN_USERNAME: admin
    DEFAULT_ADMIN_PASSWORD: password
    DEPLOYMENT_SCENARIO: PRODUCTION
    SECRET_KEY: 'ccdf5de08ac74855bda3e7e309d871e5'
    UFRAME_URL: 'http://uframe-test.ooi.rutgers.edu:12575'
    UFRAME_URL_BASE: '/sensor/inv'
    REDMINE_KEY: 'XXXXXXXXXXXXX'
    REDMINE_PROJECT_ID: 'ooi-ui-api-testing'
    UI_API_KEY: a12261fd433d4d0a8a9c6b7666d984ec
    REDMINE_URL: 'https://uframe-cm.ooi.rutgers.edu'
    REDIS_URL: 'redis://:password@localhost:6379'
  links:
   - ooiuidb
#   - redis

#docker run -d --name ooiui1 --link ooiuiservices:ooiuiservices oceanzus/ooi-ui-deploy
ooiui1:
  restart: always
  image: oceanzus/ooi-ui
  expose:
   - "5000"
  environment:
    SECRET_KEY: 'ccdf5de08ac74855bda3e7e309d871e5'
    UI_API_KEY: a12261fd433d4d0a8a9c6b7666d984ec
    HOST_NIC: eth0
  links:
   - ooiuiservices

#docker run -d --name ooiui2 --link ooiuiservices:ooiuiservices oceanzus/ooi-ui-deploy
ooiui2:
  restart: always
  image: oceanzus/ooi-ui
  expose:
   - "5000"
  environment:
    SECRET_KEY: 'ccdf5de08ac74855bda3e7e309d871e5'
    UI_API_KEY: a12261fd433d4d0a8a9c6b7666d984ec
    HOST_NIC: eth0
  links:
   - ooiuiservices

#docker run -d --link ooiui1:ooiui1 --link ooiui2:ooiui2 --name ooiui-haproxy -e PORT=5000 -p 10.181.61.91:80:80 oceanzus/haproxy
ooiuihaproxy:
  restart: always
  image: oceanzus/haproxy
  environment:
    PORT: 5000
    MAXCONN: 500
  ports:
   - "10.181.93.144:80:80"
  links:
   - ooiui1
   - ooiui2
